import json

nb = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 🌿 EfficientNet-B0 — Crop Disease Classification\n",
    "\n",
    "Training on **Crop Pest and Disease Detection** dataset (by Nirmal Sankalana).\n",
    "We filter for **Cassava, Maize, and Tomato** classes only (skip Cashew).\n",
    "\n",
    "**Setup:**\n",
    "1. Add dataset: `nirmalsankalana/crop-pest-and-disease-detection`\n",
    "2. Enable **GPU P100** or **T4 x2**\n",
    "3. Run All"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 1 — Verify dataset path\n",
    "import os\n",
    "!ls /kaggle/input/\n",
    "print('---')\n",
    "# List contents of the dataset folder\n",
    "base = '/kaggle/input/crop-pest-and-disease-detection'\n",
    "if os.path.exists(base):\n",
    "    for item in sorted(os.listdir(base)):\n",
    "        print(item)\n",
    "else:\n",
    "    print('Dataset not found at expected path. Check !ls output above and update DATA_ROOT below.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import Dataset, DataLoader, random_split\n",
    "from torchvision import transforms\n",
    "from torchvision.models import efficientnet_b0, EfficientNet_B0_Weights\n",
    "from PIL import Image\n",
    "from sklearn.metrics import classification_report\n",
    "from tqdm.auto import tqdm\n",
    "import numpy as np\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# ═══════════════════════════════════════════\n",
    "#  CONFIGURATION — update DATA_ROOT if needed\n",
    "# ═══════════════════════════════════════════\n",
    "DATA_ROOT = '/kaggle/input/crop-pest-and-disease-detection'\n",
    "\n",
    "BATCH_SIZE  = 64\n",
    "EPOCHS      = 15\n",
    "LR          = 1e-3\n",
    "NUM_WORKERS = 4\n",
    "IMG_SIZE    = 224\n",
    "VAL_SPLIT   = 0.20   # 80/20 train-val split\n",
    "SEED        = 42\n",
    "\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f'Device: {device}')\n",
    "if device.type == 'cuda':\n",
    "    print(f'GPU: {torch.cuda.get_device_name(0)}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ═══════════════════════════════════════\n",
    "#  DATASET — flat folder structure\n",
    "# ═══════════════════════════════════════\n",
    "# This dataset has folders like:\n",
    "#   Cassava bacterial blight/\n",
    "#   Cassava brown spot/\n",
    "#   Maize healthy/\n",
    "#   Tomato leaf curl/\n",
    "#   Cashew anthracnose/   <-- we SKIP these\n",
    "\n",
    "ALLOWED_PREFIXES = ('Cassava', 'Maize', 'Tomato')\n",
    "\n",
    "class CropDiseaseDataset(Dataset):\n",
    "    def __init__(self, root_dir, transform=None):\n",
    "        self.image_paths = []\n",
    "        self.labels = []\n",
    "        self.transform = transform\n",
    "        \n",
    "        # Discover class folders, filtering for our crops only\n",
    "        all_folders = sorted([\n",
    "            d for d in os.listdir(root_dir)\n",
    "            if os.path.isdir(os.path.join(root_dir, d))\n",
    "               and d.startswith(ALLOWED_PREFIXES)\n",
    "        ])\n",
    "        \n",
    "        # Clean up class names: 'Cassava brown spot' -> 'Cassava_Brown_Spot'\n",
    "        self.classes = []\n",
    "        self.folder_to_class = {}\n",
    "        for folder in all_folders:\n",
    "            clean_name = '_'.join(word.capitalize() for word in folder.split())\n",
    "            self.classes.append(clean_name)\n",
    "            self.folder_to_class[folder] = clean_name\n",
    "        \n",
    "        self.class_to_idx = {c: i for i, c in enumerate(self.classes)}\n",
    "        \n",
    "        # Collect all images\n",
    "        for folder, class_name in self.folder_to_class.items():\n",
    "            folder_path = os.path.join(root_dir, folder)\n",
    "            for fname in os.listdir(folder_path):\n",
    "                if fname.lower().endswith(('.jpg', '.jpeg', '.png')):\n",
    "                    self.image_paths.append(os.path.join(folder_path, fname))\n",
    "                    self.labels.append(self.class_to_idx[class_name])\n",
    "        \n",
    "        print(f'Found {len(self.image_paths)} images across {len(self.classes)} classes')\n",
    "        for i, c in enumerate(self.classes):\n",
    "            count = self.labels.count(i)\n",
    "            print(f'  [{i:2d}] {c}: {count} images')\n",
    "    \n",
    "    def __len__(self):\n",
    "        return len(self.image_paths)\n",
    "    \n",
    "    def __getitem__(self, idx):\n",
    "        img = Image.open(self.image_paths[idx]).convert('RGB')\n",
    "        if self.transform:\n",
    "            img = self.transform(img)\n",
    "        return img, self.labels[idx]\n",
    "\n",
    "\n",
    "# --- Transforms ---\n",
    "train_transform = transforms.Compose([\n",
    "    transforms.Resize((IMG_SIZE, IMG_SIZE)),\n",
    "    transforms.RandomHorizontalFlip(),\n",
    "    transforms.RandomVerticalFlip(),\n",
    "    transforms.RandomRotation(15),\n",
    "    transforms.ColorJitter(brightness=0.2, contrast=0.2),\n",
    "    transforms.ToTensor(),\n",
    "    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),\n",
    "])\n",
    "\n",
    "val_transform = transforms.Compose([\n",
    "    transforms.Resize((IMG_SIZE, IMG_SIZE)),\n",
    "    transforms.ToTensor(),\n",
    "    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),\n",
    "])\n",
    "\n",
    "\n",
    "# --- Load full dataset, then split ---\n",
    "full_dataset = CropDiseaseDataset(DATA_ROOT, transform=None)  # transforms applied later\n",
    "NUM_CLASSES  = len(full_dataset.classes)\n",
    "\n",
    "total       = len(full_dataset)\n",
    "val_size    = int(total * VAL_SPLIT)\n",
    "train_size  = total - val_size\n",
    "\n",
    "torch.manual_seed(SEED)\n",
    "train_subset, val_subset = random_split(full_dataset, [train_size, val_size])\n",
    "\n",
    "\n",
    "# Wrapper to apply different transforms to train vs val\n",
    "class TransformSubset(Dataset):\n",
    "    def __init__(self, subset, transform):\n",
    "        self.subset = subset\n",
    "        self.transform = transform\n",
    "    def __len__(self):\n",
    "        return len(self.subset)\n",
    "    def __getitem__(self, idx):\n",
    "        img, label = self.subset[idx]\n",
    "        if self.transform:\n",
    "            img = self.transform(img)\n",
    "        return img, label\n",
    "\n",
    "\n",
    "train_ds = TransformSubset(train_subset, train_transform)\n",
    "val_ds   = TransformSubset(val_subset,   val_transform)\n",
    "\n",
    "train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=NUM_WORKERS, pin_memory=True)\n",
    "val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS, pin_memory=True)\n",
    "\n",
    "print(f'\\nTrain: {train_size} | Val: {val_size} | Classes: {NUM_CLASSES}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ═══════════════════════════════════════\n",
    "#  MODEL\n",
    "# ═══════════════════════════════════════\n",
    "class FLEfficientNet(nn.Module):\n",
    "    def __init__(self, num_classes):\n",
    "        super().__init__()\n",
    "        self.backbone = efficientnet_b0(weights=EfficientNet_B0_Weights.DEFAULT)\n",
    "        in_features = self.backbone.classifier[1].in_features\n",
    "        self.backbone.classifier[1] = nn.Sequential(\n",
    "            nn.Dropout(p=0.3, inplace=True),\n",
    "            nn.Linear(in_features, num_classes),\n",
    "        )\n",
    "    def forward(self, x):\n",
    "        return self.backbone(x)\n",
    "\n",
    "model     = FLEfficientNet(NUM_CLASSES).to(device)\n",
    "criterion = nn.CrossEntropyLoss()\n",
    "optimizer = optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-4)\n",
    "scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', factor=0.5, patience=2, verbose=True)\n",
    "scaler    = torch.amp.GradScaler('cuda')\n",
    "\n",
    "print(f'Model ready — {NUM_CLASSES} output classes')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ═══════════════════════════════════════\n",
    "#  TRAINING LOOP\n",
    "# ═══════════════════════════════════════\n",
    "best_acc = 0.0\n",
    "history  = {'train_acc': [], 'val_acc': [], 'train_loss': [], 'val_loss': []}\n",
    "\n",
    "for epoch in range(EPOCHS):\n",
    "    # --- Train ---\n",
    "    model.train()\n",
    "    running_loss, correct, total = 0.0, 0, 0\n",
    "    pbar = tqdm(train_loader, desc=f'Epoch {epoch+1}/{EPOCHS} [Train]')\n",
    "    \n",
    "    for imgs, labels in pbar:\n",
    "        imgs, labels = imgs.to(device), labels.to(device)\n",
    "        optimizer.zero_grad()\n",
    "        \n",
    "        with torch.amp.autocast('cuda'):\n",
    "            out  = model(imgs)\n",
    "            loss = criterion(out, labels)\n",
    "        \n",
    "        scaler.scale(loss).backward()\n",
    "        scaler.step(optimizer)\n",
    "        scaler.update()\n",
    "        \n",
    "        running_loss += loss.item() * imgs.size(0)\n",
    "        correct += (out.argmax(1) == labels).sum().item()\n",
    "        total   += labels.size(0)\n",
    "        pbar.set_postfix(loss=f'{loss.item():.4f}', acc=f'{correct/total:.4f}')\n",
    "    \n",
    "    train_acc  = correct / total\n",
    "    train_loss = running_loss / total\n",
    "    \n",
    "    # --- Validate ---\n",
    "    model.eval()\n",
    "    running_loss, correct, total = 0.0, 0, 0\n",
    "    all_preds, all_labels = [], []\n",
    "    \n",
    "    with torch.no_grad():\n",
    "        for imgs, labels in tqdm(val_loader, desc=f'Epoch {epoch+1}/{EPOCHS} [Val]'):\n",
    "            imgs, labels = imgs.to(device), labels.to(device)\n",
    "            out  = model(imgs)\n",
    "            loss = criterion(out, labels)\n",
    "            \n",
    "            running_loss += loss.item() * imgs.size(0)\n",
    "            preds = out.argmax(1)\n",
    "            correct += (preds == labels).sum().item()\n",
    "            total   += labels.size(0)\n",
    "            all_preds.extend(preds.cpu().numpy())\n",
    "            all_labels.extend(labels.cpu().numpy())\n",
    "    \n",
    "    val_acc  = correct / total\n",
    "    val_loss = running_loss / total\n",
    "    scheduler.step(val_acc)\n",
    "    \n",
    "    history['train_acc'].append(train_acc)\n",
    "    history['val_acc'].append(val_acc)\n",
    "    history['train_loss'].append(train_loss)\n",
    "    history['val_loss'].append(val_loss)\n",
    "    \n",
    "    marker = ''\n",
    "    if val_acc > best_acc:\n",
    "        best_acc = val_acc\n",
    "        torch.save(model.state_dict(), 'best_efficientnet.pth')\n",
    "        marker = ' ⭐ SAVED'\n",
    "    \n",
    "    print(f'Epoch {epoch+1}: Train {train_acc:.4f} | Val {val_acc:.4f} | Loss {val_loss:.4f}{marker}')\n",
    "\n",
    "print(f'\\n✅ Training complete! Best val accuracy: {best_acc:.4f}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ═══════════════════════════════════════\n",
    "#  EVALUATION + PLOTS\n",
    "# ═══════════════════════════════════════\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Load best model\n",
    "model.load_state_dict(torch.load('best_efficientnet.pth'))\n",
    "model.eval()\n",
    "\n",
    "# Classification report\n",
    "print('Classification Report:')\n",
    "print(classification_report(all_labels, all_preds, target_names=full_dataset.classes))\n",
    "\n",
    "# Training curves\n",
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))\n",
    "ax1.plot(history['train_acc'], label='Train')\n",
    "ax1.plot(history['val_acc'],   label='Val')\n",
    "ax1.set_title('Accuracy'); ax1.legend()\n",
    "ax2.plot(history['train_loss'], label='Train')\n",
    "ax2.plot(history['val_loss'],   label='Val')\n",
    "ax2.set_title('Loss'); ax2.legend()\n",
    "plt.tight_layout()\n",
    "plt.savefig('training_curves.png', dpi=150)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ═══════════════════════════════════════\n",
    "#  OUTPUT — Copy these into src/config.py\n",
    "# ═══════════════════════════════════════\n",
    "print('=' * 60)\n",
    "print('COPY THE FOLLOWING INTO src/config.py')\n",
    "print('=' * 60)\n",
    "print()\n",
    "print(f'NUM_CLASSES: int = {NUM_CLASSES}')\n",
    "print()\n",
    "print('CLASS_NAMES: List[str] = [')\n",
    "for c in full_dataset.classes:\n",
    "    print(f\"    '{c}',\")\n",
    "print(']')\n",
    "print()\n",
    "print('=' * 60)\n",
    "print('Download best_efficientnet.pth from the Output tab on the right →')\n",
    "print('Then place it in your project: models/best_efficientnet.pth')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open('/Users/lokeshverma/Desktop/gitProj/FinalYearProject/notebooks/train_kaggle_efficientnet_new.ipynb', 'w') as f:
    json.dump(nb, f, indent=1)

print('✅ Notebook generated successfully.')
